version: '3.8'
services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.0
    volumes:
      - ./influx/database:/var/lib/influxdb2
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${influx_user}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${influx_pw}
      - DOCKER_INFLUXDB_INIT_ORG=${influx_org}
      - DOCKER_INFLUXDB_INIT_BUCKET=${influx_bucket}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${influx_token}
    ports:
      - "8086:8086"   # Required for access to GUI
  
  web-scraper:
    container_name: scrapcrab
    image: scrapcrab:0.1
    env_file:
      - .env
    environment:
      - influxdb_url=$influxdb.container_name
      - REFRESH_INTERVAL_MINUTES=30
    command: python scheduled_scraper.py